# New carousel specs. Each: id, kind, hook, five body slides, caption lead (before CTA).
# Facts are limited to cited sources (NAEP 2024, National Literacy Trust 2025) or plain math/opinion.
# Body slide text may end with "||Source: ..." to show a small source line.
TAGS = {
 "founder": "#studentfounder #screentime #readingapp #raisingreaders #buildinpublic",
 "pick":    "#thisorthat #parenting #screentime #kidsbooks #raisingreaders",
 "sat":     "#sat #studytips #reading #studentlife #literacy",
 "res":     "#literacy #readingmatters #parentingstats #education #raisingreaders",
 "books":   "#kidsbooks #bookrecs #raisingreaders #reading #middlegrade",
}
POSTS = [
# ---------- founder (student voice, only things that are true) ----------
("f1-why-i-built-it","founder","I'm a student. I built a reading app because of a screen time fight.",
 ["My mom and my sister argue about screen time all the time.",
  "When I was a kid, I wished I could earn tickets for screen time.",
  "Tickets I could use whenever I wanted, not a strict daily limit.",
  "So ReadBank works like that. You read. You earn screen time. You spend it.",
  "I also wish I had read more when I was younger. It would have helped my English and tests like the SAT."],
 "I'm a student, not a parent. I built ReadBank because of a real screen time fight at my house, and because I wish I had read more when I was younger. What do you wish you had started earlier? Tell me below."),
("f2-comprehension-checks","founder","Anyone can flip pages. So ReadBank checks that you actually read.",
 ["Most reading rewards only count time or pages.",
  "A kid can tap through a book without reading a word.",
  "So after a chapter, ReadBank starts a short conversation about what happened.",
  "It is not a multiple choice quiz. It asks about the story.",
  "If you can explain it, you earn the screen time. That is the point."],
 "This is the part of ReadBank I care about most. Would you trust a reading app that only counts pages? Comment YES or NO."),
("f3-screen-time-bank","founder","The Screen Time Bank, explained in 30 seconds.",
 ["Read a chapter and earn screen time minutes.",
  "The minutes go into a bank that keeps building.",
  "The balance is always visible, so there is nothing to argue about.",
  "Spend the minutes on screen time whenever you want.",
  "Or save up for a buddy animal instead."],
 "Would you rather earn your screen time or get a fixed daily limit? Comment EARN or LIMIT."),
("f4-what-parents-see","founder","What a parent sees in ReadBank.",
 ["What your kid is reading.",
  "How much screen time they have earned.",
  "Badges and progress over time.",
  "No more asking twice and no more guessing.",
  "Parents see everything. Kids see their own balance."],
 "Parents get a clear view, kids get something to work toward. What would you want to see most? Tell me in the comments."),
("f5-it-all-counts","founder","Graphic novels, classics, series. It all counts.",
 ["A lot of reading rewards only count certain books.",
  "ReadBank has classics and graphic novels in the library.",
  "Reading the book you actually want is how a habit starts.",
  "The goal is a kid who reads, not a kid who read what they were told to.",
  "Pick what you like. Earn screen time for it."],
 "What counts as reading in your house? Graphic novels, audiobooks, comics? Tell me below."),
("f6-things-i-wish-i-knew","founder","5 things I wish I knew about reading when I was younger.",
 ["1. Reading builds vocabulary without trying.",
  "2. Reading less when you are young makes it harder to catch up later.",
  "3. You do not have to finish every book.",
  "4. Hard books get easier with practice.",
  "5. The best time to start is now."],
 "I'm a student and I wish I had read more earlier. Which one hits for you? Comment the number."),
("f7-earn-vs-limit","founder","Why I think earning beats a strict limit.",
 ["A limit says: you get this much, no matter what.",
  "Earning says: your effort changes the outcome.",
  "When I was a kid, I wanted control over my own time.",
  "Earned time feels like yours. A limit feels like a rule.",
  "That is the idea behind ReadBank."],
 "Was it a limit or did you earn it when you were a kid? Tell me below."),
# ---------- pick one (comment bait) ----------
("p1-reading-first","pick","Screen time first or reading first? Pick one.",
 ["Option 1: Reading first. Earn it, then use it.",
  "Option 2: Screens first. Read after.",
  "Many families end up in option 2 and the reading gets squeezed out.",
  "In ReadBank, reading comes first because it earns the time.",
  "Comment 1 or 2."],
 "Pick one and tell me why. Comment 1 or 2."),
("p2-audio-or-paper","pick","Audiobook or paper book? Pick one.",
 ["Option 1: Audiobook. Listen anywhere.",
  "Option 2: Paper book. See every word.",
  "Audiobooks build listening and vocabulary. Print builds decoding.",
  "Many readers use both.",
  "Comment 1 or 2."],
 "Which one do you actually use? Comment 1 or 2."),
("p3-series-or-standalone","pick","Series or one-off book? Pick one.",
 ["Option 1: A series. You already know the characters.",
  "Option 2: A standalone. Finish it and move on.",
  "A series is an easy way to keep a reluctant reader going.",
  "A standalone is an easier start for some readers.",
  "Comment 1 or 2."],
 "Series people or standalone people? Comment 1 or 2."),
("p4-car-or-bedtime","pick","Reading in the car or at bedtime? Pick one.",
 ["Option 1: The car. Time that would be wasted anyway.",
  "Option 2: Bedtime. A calm way to end the day.",
  "Both are 10 minute windows most kids already have.",
  "Small windows add up fast.",
  "Comment 1 or 2."],
 "Which window works better in your house? Comment 1 or 2."),
("p5-limit-or-earn","pick","A fixed screen time limit or earning your time? Pick one.",
 ["Option 1: A fixed limit. Simple and the same every day.",
  "Option 2: Earn it. Your effort changes the amount.",
  "A limit is easy to set. Earning gives kids control.",
  "Which would you have picked as a kid?",
  "Comment 1 or 2."],
 "Which would you have picked as a kid? Comment 1 or 2."),
("p6-classic-or-new","pick","Classic or new release? Pick one.",
 ["Option 1: A classic. It has lasted for a reason.",
  "Option 2: A new release. Everyone is talking about it.",
  "Classics build stamina. New books build excitement.",
  "A good reading habit has both.",
  "Comment 1 or 2."],
 "Classic or new release? Comment 1 or 2."),
("p7-library-or-bookstore","pick","Library or bookstore? Pick one.",
 ["Option 1: The library. Free and endless.",
  "Option 2: The bookstore. You get to keep it.",
  "A library card is one of the cheapest tools a family has.",
  "A bookstore trip can make reading feel special.",
  "Comment 1 or 2."],
 "Library or bookstore? Comment 1 or 2."),
("p8-movie-or-book-first","pick","Movie first or book first? Pick one.",
 ["Option 1: Book first. Picture it yourself.",
  "Option 2: Movie first. Then read to see what changed.",
  "Seeing the movie first can make a long book less scary.",
  "Reading first lets you imagine it your way.",
  "Comment 1 or 2."],
 "Book first or movie first? Comment 1 or 2."),
("p9-ten-minutes","pick","10 minutes of reading or 10 minutes of scrolling? Pick one.",
 ["Option 1: 10 minutes of reading.",
  "Option 2: 10 minutes of scrolling.",
  "10 minutes a day is about 61 hours of reading in a year.",
  "That is a lot of books.",
  "Comment 1 or 2."],
 "Be honest. Comment 1 or 2."),
# ---------- SAT / study (student voice, no unverified stats) ----------
("s1-digital-sat-reading","sat","What the digital SAT reading section looks like.",
 ["The digital SAT Reading and Writing section uses short passages.",
  "Each passage comes with one question.",
  "So you read a little, answer, and move on.",
  "Fast, careful reading matters.",
  "That is a skill you build by reading a lot.||Source: College Board"],
 "I'm a student and this is the part I wish I had prepared for earlier. Taking the SAT soon? Tell me below."),
("s2-five-habits","sat","5 reading habits that help on test day.",
 ["1. Read something every day, even for 10 minutes.",
  "2. Look up words you do not know.",
  "3. After each page, say the main idea in one sentence.",
  "4. Notice words like but and however.",
  "5. If you get lost, re-read the first sentence."],
 "Save this for study season. Which habit do you already do?"),
("s3-words-from-books","sat","Learn words from books, not lists.",
 ["Flashcards teach a word once.",
  "Books show a word used in real sentences.",
  "Seeing it again in a new story makes it stick.",
  "When you meet a new word, guess the meaning from the sentence first.",
  "Then check. Guessing from context is a skill tests ask for."],
 "Save this. What is the last new word you learned from a book?"),
("s4-hard-passage","sat","How to read a hard passage.",
 ["Slow down on the first sentence. It sets up the topic.",
  "Find the main idea before the details.",
  "Mark contrast words like but, however, and although.",
  "Do not stop at a word you do not know. Keep going and guess.",
  "Say the passage back in one sentence. If you can, you got it."],
 "Save this for your next reading test."),
("s5-ten-minutes","sat","What 10 minutes a day adds up to.",
 ["10 minutes a day is 70 minutes a week.",
  "70 minutes a week is about 300 minutes a month.",
  "That is about 61 hours of reading in a year.",
  "No big plan. Just a small window every day.",
  "Start with today."],
 "10 minutes. That is all. Save this and try it for a week."),
("s6-finish-a-book","sat","How to finish a book you do not want to read.",
 ["Set a timer for 10 minutes. Stop when it ends.",
  "Pair the print book with the audiobook.",
  "Change the book, not the habit.",
  "If you hate it after 50 pages, it is okay to quit.",
  "The goal is to keep reading, not to win a book."],
 "Do you quit books or finish them no matter what? Tell me below."),
("s7-transition-words","sat","5 small words that tell you where a passage is going.",
 ["However and but: a contrast is coming.",
  "Therefore: this is the result.",
  "For example: this is the proof.",
  "Although: a twist, then the real point.",
  "Similarly: another example of the same idea."],
 "Save this. These show up in almost every passage."),
# ---------- research (cited) ----------
("r1-naep-grade4","res","40% of 4th graders read below the basic level.",
 ["The 2024 Nation's Report Card tested reading in grades 4 and 8.",
  "In grade 4, 40% scored below NAEP Basic.",
  "31% scored at or above Proficient.",
  "The average score fell 2 points from 2022 and 5 points from 2019.",
  "Reading is a habit. Habits start small.||Source: NAEP 2024 Reading, Nation's Report Card"],
 "The numbers are hard to ignore. Save this and send it to someone who cares about reading."),
("r2-naep-grade8","res","A third of 8th graders read below the basic level.",
 ["In 2024, 33% of 8th graders scored below NAEP Basic.",
  "That is the largest share recorded.",
  "The average score fell 2 points from 2022.",
  "Scores have been falling since 2019.",
  "Small daily reading adds up.||Source: NAEP 2024 Reading, Nation's Report Card"],
 "Save this and send it to a teacher or parent you know."),
("r3-nlt-enjoyment","res","Only 1 in 3 kids say they enjoy reading.",
 ["A UK survey of about 115,000 children asked about reading.",
  "32.7% of 8 to 18 year olds said they enjoy reading in their free time.",
  "That is the lowest level in 20 years.",
  "Only 18.7% read something daily in their free time.",
  "Enjoyment is something you can rebuild.||Source: National Literacy Trust, Children and young people's reading in 2025 (UK)"],
 "Save this. What would make reading fun again for you?"),
("r4-who-stopped","res","Who stopped enjoying reading the most?",
 ["The same UK survey found the drop was steepest in primary-aged children.",
  "And in boys aged 11 to 16.",
  "Reading enjoyment is down 36% since the survey started asking in 2005.",
  "That sounds like a habit problem, not a talent problem.",
  "Habits can be rebuilt.||Source: National Literacy Trust, Children and young people's reading in 2025 (UK)"],
 "Comment if you were a kid who stopped reading and why."),
# ---------- books (real titles) ----------
("b1-funny-books","books","5 funny books kids actually finish.",
 ["1. Dog Man by Dav Pilkey",
  "2. Diary of a Wimpy Kid by Jeff Kinney",
  "3. The Bad Guys by Aaron Blabey",
  "4. Big Nate by Lincoln Peirce",
  "5. Captain Underpants by Dav Pilkey"],
 "Funny books are a great way in. What was your favorite book as a kid? Drop it below."),
("b2-adventure-books","books","5 adventure books for kids who like action.",
 ["1. Hatchet by Gary Paulsen",
  "2. The Lightning Thief by Rick Riordan",
  "3. The Wild Robot by Peter Brown",
  "4. Wings of Fire by Tui T. Sutherland",
  "5. Holes by Louis Sachar"],
 "What was your favorite book as a kid? Drop it below."),
("b3-graphic-novels","books","5 graphic novels worth reading.",
 ["1. Smile by Raina Telgemeier",
  "2. Amulet by Kazu Kibuishi",
  "3. New Kid by Jerry Craft",
  "4. El Deafo by Cece Bell",
  "5. Dog Man by Dav Pilkey"],
 "Graphic novels count as reading. Drop your favorite below."),
("b4-classics","books","5 classics kids can actually finish.",
 ["1. Charlotte's Web by E.B. White",
  "2. The Hobbit by J.R.R. Tolkien",
  "3. Treasure Island by Robert Louis Stevenson",
  "4. The Call of the Wild by Jack London",
  "5. Alice's Adventures in Wonderland by Lewis Carroll"],
 "Save this list. Which classic have you actually finished?"),
]
